<?php
/**
 * Created by PhpStorm.
 * User: btm
 * Date: 11/19/14
 * Time: 2:12 PM
 */

namespace Drupal\campaignmonitor\Plugin\Block;

use Drupal\campaignmonitor\WebService\CampaignMonitorRestClient;
use Drupal\Core\block\BlockBase;
use Drupal\Component\Annotation\Plugin;
use Drupal\Core\Annotation\Translation;
use Drupal\Core\Form\FormState;
use Drupal\Core\Form\FormStateInterface;

/**
 * Provides a test block.
 *
 * @Block(
 *  id = "list_subscription_block",
 *  admin_label = @Translation("List Subscription")
 * )
 */
class CampaignMonitorListSubscriptionBlock extends BlockBase {

  /**
   * Builds and returns the renderable array for this block plugin.
   *
   * @return array
   *   A renderable array representing the content of the block.
   *
   * @see \Drupal\block\BlockViewBuilder
   */
  public function build() {
    $config = $this->getConfiguration();
    $list_id = $config['list_settings']['list_id'];

    $formBuilder = \Drupal::formBuilder();
    $form_state = new FormState();
    $form_state->setValue('list_id', $list_id);

    $response = $formBuilder->buildForm('Drupal\campaignmonitor\Form\CampaignMonitorSubscriptionForm', $form_state);

    return $response;
  }

  public function blockForm($form, FormStateInterface $form_state) {
    $form =parent::blockForm($form, $form_state);
    $cm = CampaignMonitorRestClient::getConnector();
    $lists = $cm->getLists();

    $options = array();
    foreach($lists as $id => $list) {
      $options[$id] = $list['name'];
    }

    $form['list_settings'] = array(

        '#type' => 'fieldset',
        '#title' => 'List Settings'

    );

    $config = $this->getConfiguration();

    $form['list_settings']['list_id'] = array(
      '#type' => 'select',
      '#title' => t('List'),
      '#description' => t('Which list signup form will be displayed in block?'),
      '#options' => $options,
      '#default_value' => $config['listing_settings']['list_id']
    );

    return $form; // TODO: Change the autogenerated stub
  }




}